### ISSUE TITLE
怎么是个男的！！

### ISSUE THREAD

**Issue by RobertDaiMelb** [VisionRush/DeepFakeDefenders#1]
1

**Comment by mczhuge** [comment]
看了微博，启发了我一个新路径来宣传我的工作 🙋

**Comment by DoiiarX** [comment]
![image](https://github.com/user-attachments/assets/1c1332f5-8fc1-47ee-b888-d4b8b8847efa)
好像还真是男的。乐。

**Comment by BRONYA-818** [comment]
请问楼主是串子吗 lol
