### ISSUE TITLE
Hi, is there a version for single card GPU training.

### ISSUE THREAD

**Issue by xknvjn** [VisionRush/DeepFakeDefenders#3]
Sorry, I only have one GPU, how I changed some code, but still get "`RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.`", so I would like to ask if there is a version for single card training.

**Comment by Guanzhou-Ke** [comment]
Hi, 

Thank you for your question. We have added a single gpu training version in the next version. 
When the PR has been merged, you will see the `main_train_single_gpu.py` file. 
You can directly run this script to train on a single gpu.

**Comment by xknvjn** [comment]
> 你好，
> 
> 谢谢你的提问。我们在下一个版本中增加了单 gpu 训练版本。 当 PR 合并后，你会看到该`main_train_single_gpu.py`文件。 你可以直接运行此脚本在单 gpu 上进行训练。

OK, thank you very much.

**Comment by demonloveryyw** [comment]
我的电脑也只有单GPU-_-
